### ISSUE TITLE
Stats notes

### ISSUE THREAD

**Issue by bongo227** [bongo227/StatsNotes#69]
@tpb1908 do you have the link for the stats notes you were using?

**Comment by tpb1908** [comment]
I took notes from [this](https://www.google.co.uk/url?sa=t&source=web&rct=j&url=http://www.mrbartonmaths.com/resources/a%2520level%2520revision/S3.pdf&ved=0ahUKEwj6x9Sl1LXRAhVkJ8AKHbT8D4QQFggaMAA&usg=AFQjCNHyUu4lfW5fuCy8FX7rT-zSTyiVzg&sig2=0eMCfbCCFcMsDefBg95puw).

I need to find a set of notes for the other modules.

I think that the Franklin to has books for S5/6? They are for a different body, but cover the same content.

**Comment by bongo227** [comment]
I had found some for 3 and 4 but cant find them anywhere now.

**Comment by tpb1908** [comment]
The library has OCR S3&S, Edexcel S3, and Edexcel S4.
