### ISSUE TITLE
Standard error of a statistic

### ISSUE THREAD

**Issue by bongo227** [bongo227/StatsNotes#70]
Given:
![image](https://cloud.githubusercontent.com/assets/2641780/22111263/9f588f24-de56-11e6-8357-4bd4fee582a3.png)

Then the variation would be:
![image](https://cloud.githubusercontent.com/assets/2641780/22111279/b3c9fcc2-de56-11e6-89b5-9a4443f29c7b.png)

Or at least thats what I thought it should be, the book has this:
![image](https://cloud.githubusercontent.com/assets/2641780/22111400/18556848-de57-11e6-8dec-4df6738c9ddd.png)

Have you done this yet? Does it look correct?

@tpb1908

**Comment by bongo227** [comment]
The distribution can be assumed to follow a binomial distribution

**Comment by tpb1908** [comment]
I'm not sure why the 2n in the second half of the books answer isn't squared.

Obviously to cancel the n in np(1-p) the divisor must be n^2.

**Comment by bongo227** [comment]
Thats what I had thought.

Thanks
