### ISSUE TITLE
Critical values for correlation coefficeients

### ISSUE THREAD

**Issue by bongo227** [bongo227/StatsNotes#71]
@tpb1908 have you found a way to get these on the calculator. So far I haven't needed the tables but I don't think they are on their.

**Comment by tpb1908** [comment]
I saw 
![Screenshot_20170129-133925.png](http://i.imgur.com/KvHGgIb.png) this which might be how to do it, but I didn't see a built in function.

**Comment by tpb1908** [comment]
Take a look at the bottom formula [here](http://www.danielsoper.com/statcalc/formulas.aspx?id=44l)

**Comment by tpb1908** [comment]
I found out how to do it.

Use the student_cdf function with the following arguments

n-2 , r/sqrt((1-r^2)/(n-2)), 1e99 (large value)

**Comment by bongo227** [comment]
That cant be it since the table looks up the critical value of r, you only have the significance level and sample size:
![image](https://cloud.githubusercontent.com/assets/2641780/22404533/7e8b0df4-e62a-11e6-921c-7c32a6091e0e.png)

**Comment by bongo227** [comment]
student_cdf(n-2 , r/sqrt((1-r^2)/(n-2)), 1e99 (large value)) gives you the Pearson correlation coefficient, which I havnt done yet.

**Comment by tpb1908** [comment]
Sorry, the only other formulae I have found are [here](http://stats.stackexchange.com/questions/7394/how-to-estimate-a-critical-value-of-spearmans-correlation-for-n-100) and they are all approximations for n > 30.

Might have to resort to using the tables.

**Comment by bongo227** [comment]
Thats a shame, not to bad though.

I just ordered these books:
- Advancing Maths for AQA: Statistics 4 (S4)
- Statistics: Bk. 5 (Heinemann Modular Mathematics for Edexcel AS and A Level)
- Advancing Maths for AQA: Statistics 7 (S7)
- Advancing Maths for AQA Statistics 3 and 6

They where pretty cheap used so I thought, why not. You welcome to borrow any when they arrive.
