### ISSUE TITLE
SS04 June 2007

### ISSUE THREAD

**Issue by bongo227** [bongo227/StatsNotes#75]
Question paper:

> Suggest two factors, other than your calculations, which might influence Abu’s decision
as to which queue to join.

Markscheme:

> amount in baskets of queue members, attractiveness/speed/demeanour of checkout assistant/presence of noisy children in queue.

Some of these stats questions are weird...

**Comment by tpb1908** [comment]
I suppose the first one makes sense.
However I fail to see the relevance of any of the others to a statistics course, unless we are to begin conducting tests on the attractiveness of cashiers.

Then again, knowing AQA, that doesn't seem so unlikely.
